### ISSUE TITLE
Pleuston Plankton refactor

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/pleuston#24]
The idea is to list the things to refactor in the Pleuston side (sorted by priority):

- [x] eject from `create-react-app` and create our own build process (#28 & #77)
- [x] switch to production build in Dockerfile (#31)
- [ ] orders: should be just a category/state of an asset (#60)
- [x] enable pleuston to connect to kovan network (artifacts have to be loaded from different location) (#50)
- [x] UI pattern for required input fields (#40)
- [x] description is missing in AssetFull view (#41)
- [x] Refactor web3 keeper interactions into separate library (#68 & #69)
- [x] make sure metadata field names are in sync with what's displayed, used in pleuston, and used in provider (will be done as part of OEP-08, see #98)
- [ ] investigate and fix high amount of requests (#39)
- [ ] metadata response is weirdly escaped (#37)
- [x] setup Codacy code coverage (#47)
- [x] Automate docker Push #55
- [x] Webpack & Babel & CSS modules updates (#77)

After reviewing this, each entry will be an independent user story to be implemented in the following days.

**Comment by kremalicious** [comment]
initial refactoring is done, remaining tasks have been moved into issues
